project_id = "uacernprfbnascyfrkrb"

[functions.health-check]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-deletion-code]
verify_jwt = true

[functions.delete-pharmacy]
verify_jwt = true

[functions.send-admin-invite]
verify_jwt = true